name: CI/CD Deploy

on:
  push:
    branches: [ "deploy" ]   # Запускается при каждом push в ветку deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}       # IP сервера (77.221.143.122)
          username: ${{ secrets.SERVER_USER }}   # Пользователь (root)
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # Приватный SSH-ключ
          script: |
            if [ ! -d "/root/tg_bot" ]; then
              git clone https://github.com/emel1ch/tg_bot.git /root/tg_bot
            fi
            cd /root/tg_bot
            git fetch origin
            git reset --hard origin/deploy
            docker-compose up -d --build
